const task = await taskSpace(config.spaceId ?? 'scheduling-review');
console.log({ spaceId: task.spaceId });
const page = task.page('p1');
const evidence = {};
await page.goto(config.url);
await page.waitForFunction(() => document.body.textContent?.includes('account-a.json'));
await page.evaluate(() => window.routingBoardActions.delayCheck());
await page.click('loc=css:[data-routing-auth-id="account-A"] [data-routing-action="recheck"]');
await page.waitForFunction(() => window.routingBoardActions.requests().checks.length === 1);
await page.evaluate(() => window.routingBoardActions.switchConnection());
// Wait for a rendered connection change without waiting for the 15-second poll.
await page.evaluate(() => new Promise((resolve) => requestAnimationFrame(() => requestAnimationFrame(resolve))));
evidence.switched = await page.evaluate(() => document.body.textContent?.includes('account-b.json'));
await page.evaluate(() => window.routingBoardActions.finishCheck());
await page.evaluate(() => new Promise((resolve) => requestAnimationFrame(() => requestAnimationFrame(resolve))));
evidence.staleNotifications = await page.evaluate(() => window.routingBoardActions.notifications().length);
await page.reload();
await page.waitForFunction(() => document.body.textContent?.includes('account-a.json'));
await page.click('loc=css:[data-routing-auth-id="account-A"] [data-routing-action="resume"]');
await page.waitForFunction(() => document.querySelector('[role="dialog"]'));
await page.evaluate(() => window.routingBoardActions.switchConnection());
await page.evaluate(() => new Promise((resolve) => requestAnimationFrame(() => requestAnimationFrame(resolve))));
await page.click('loc=role:button[name="确认恢复"]');
await page.evaluate(() => new Promise((resolve) => requestAnimationFrame(() => requestAnimationFrame(resolve))));
evidence.staleReleases = await page.evaluate(() => window.routingBoardActions.requests().releases.length);
await page.reload();
await page.waitForFunction(() => document.body.textContent?.includes('account-a.json'));
await page.evaluate(() => window.routingBoardActions.delayGet());
await page.click('loc=css:[data-routing-auth-id="account-A"] [data-routing-action="recheck"]');
await page.waitForFunction(() => window.routingBoardActions.requests().getCount === 2);
await page.evaluate(() => window.routingBoardActions.switchConnection());
await page.evaluate(() => new Promise((resolve) => requestAnimationFrame(() => requestAnimationFrame(resolve))));
await page.evaluate(() => window.routingBoardActions.finishGet());
await page.evaluate(() => new Promise((resolve) => requestAnimationFrame(() => requestAnimationFrame(resolve))));
evidence.staleRefreshNotifications = await page.evaluate(() => window.routingBoardActions.notifications().length);
const passed = evidence.switched && evidence.staleNotifications === 0 && evidence.staleReleases === 0 && evidence.staleRefreshNotifications === 0;
const fs = await import('node:fs/promises');
await fs.mkdir(config.artifactDir, { recursive: true });
await fs.writeFile(`${config.artifactDir}/lifecycle.json`, JSON.stringify({ passed, evidence }, null, 2));
console.log({ passed, evidence });
if (passed === Boolean(config.expectBefore)) throw new Error('Unexpected lifecycle result');
