name: Cleanup old workflow runs

on:
  workflow_dispatch:
  schedule:
    - cron: '37 2 * * *'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  cleanup-runs:
    runs-on: ubuntu-latest

    permissions:
      actions: write
      contents: read

    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@0cf693bc9909e5e867ee8f27b813224ba862939c # v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 7
          keep_minimum_runs: 6
